# Generated by Django 3.2.18 on 2023-11-24 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=256)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association', models.FloatField()),
                ('from_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_related_posts', to='posts.post')),
                ('to_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_related_posts', to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField()),
                ('association', models.FloatField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.totalword')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='related_post',
            field=models.ManyToManyField(through='posts.RelatedPost', to='posts.Post'),
        ),
    ]
