# Generated by Django 3.2.18 on 2023-11-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetail',
            name='association',
            field=models.FloatField(null=True),
        ),
    ]
