# Generated by Django 3.2.18 on 2023-11-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_postdetail_association'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdetail',
            name='association',
        ),
        migrations.AlterField(
            model_name='relatedpost',
            name='association',
            field=models.IntegerField(),
        ),
    ]
